defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  04a16e93-e7d3-45fb-b856-6cccc813b684: # crafttut
    enabledByDefault: true
    hasUrls: true
    template: singles/about
    uriFormat: about
type: single
